data = [
  { "id" : "DeepakPritChan", "name" : "Deepak", "gender" : "Male", "parent" : "PrithKhimRata", "spouse" : "Jyoti", "DOB" : "1984", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "rupandehi" },
  { "id" : "DezyanDeepJyot", "name" : "Dezyan", "gender" : "Male", "parent" : "DeepakPritChan", "spouse" : "NA", "DOB" : "2013", "birthplace" : "California, USA", "notes" : "", "currentlocation" : "" },
  { "id" : "IshaanDeepJyot", "name" : "Ishaan", "gender" : "Male", "parent" : "DeepakPritChan", "spouse" : "NA", "DOB" : "2015", "birthplace" : "Oregion, USA", "notes" : "", "currentlocation" : "" },
  { "id" : "NarayanPritChan", "name" : "Narayan", "gender" : "Male", "parent" : "PrithKhimRata", "spouse" : "Maya", "DOB" : "1981", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "DikchyaNaraMaya", "name" : "Dikchya", "gender" : "Female", "parent" : "NarayanPritChan", "spouse" : "NA", "DOB" : "2004", "birthplace" : "Sunwal, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SamikshaNaraMaya", "name" : "Samiksha", "gender" : "Female", "parent" : "NarayanPritChan", "spouse" : "NA", "DOB" : "2012", "birthplace" : "Sunwal, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "KeshavNaraMaya", "name" : "Keshav", "gender" : "Male", "parent" : "NarayanPritChan", "spouse" : "NA", "DOB" : "2014", "birthplace" : "Sunwal, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "IshwariKhimRata", "name" : "Ishwari", "gender" : "Female", "parent" : "KhimTopPuni", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "KhemKhimRata", "name" : "Khem Bahadur", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Kamala", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PrithKhimRata", "name" : "Prith Bahadur", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Chandrakala", "DOB" : "1959", "birthplace" : "Gulmi, Nepal", "notes" : "Moved to  Sukkhanagar, Butwal", "currentlocation" : "" },
  { "id" : "DeviKhemKama", "name" : "Devi", "gender" : "Female", "parent" : "KhemKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BijayaKhemKama", "name" : "Bijaya", "gender" : "Male", "parent" : "KhemKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BishalKhemKama", "name" : "Bishal", "gender" : "Male", "parent" : "KhemKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "MayanKhimRata", "name" : "Mayan", "gender" : "Female", "parent" : "KhimTopPuni", "spouse" : "Basnet", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "DilKhimRata", "name" : "Dil Bahadur", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Meena", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "Moved to Khairani, Nawalparsi", "currentlocation" : "" },
  { "id" : "MeeraDilMeen", "name" : "Meera", "gender" : "Female", "parent" : "DilKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "RamDilMeen", "name" : "Ram", "gender" : "Male", "parent" : "DilKhimRata", "spouse" : "Ganga", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "RajinRamGang", "name" : "Rajin", "gender" : "Male", "parent" : "RamDilMeen", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SumanDilMeen", "name" : "Suman", "gender" : "Female", "parent" : "DilKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "DevKhimRata", "name" : "Dev Bahadur", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Balkumari", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "AlinaDevBalk", "name" : "Alina", "gender" : "Female", "parent" : "DevKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "AsuDevBalk", "name" : "Asu", "gender" : "Female", "parent" : "DevKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "AbuDevBalk", "name" : "Abu", "gender" : "Female", "parent" : "DevKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "TekKhimRata", "name" : "Tek Bahadur", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Sita", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "Moved to Sunwal Gaidakhal, Nawalparasi", "currentlocation" : "" },
  { "id" : "JyotiTekSita", "name" : "Jyoti", "gender" : "Female", "parent" : "TekKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "MahendraTekSita", "name" : "Mahendra", "gender" : "Male", "parent" : "TekKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "TikaKhimRata", "name" : "Tika Bahadur", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Meena", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SamijaTikaMeen", "name" : "Samija", "gender" : "Female", "parent" : "TikaKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SubhaamTikaMeen", "name" : "Subhaam", "gender" : "Male", "parent" : "TikaKhimRata", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SarbaKhimRata", "name" : "Sarba", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Shova", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "MukutKhimRata", "name" : "Mukut", "gender" : "Male", "parent" : "KhimTopPuni", "spouse" : "Meena", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "OmTopPuni", "name" : "Om Bahadur", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Drupati-Phulmati", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "KhimTopPuni", "name" : "Khim Bahadur", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "RatanaKumari-ThanKumari", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "MaanTopPuni", "name" : "Maan Kumari", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Gharti", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "JhabiTopPuni", "name" : "Jhabi", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Kunwar", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BalkumariTopPuni", "name" : "Balkumari", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Karki", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PurnaKaliTopPuni", "name" : "PurnaKali", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Khatri", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BhupalTopPuni", "name" : "Bhupal Bahadur", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Yam Kumari", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "KhagiTopPuni", "name" : "Khagi", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Adhikari", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "DurgaTopPuni", "name" : "Durga", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Meena", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "IshwariTopPuni", "name" : "Ishwari", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Khati", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "KalikaTopPuni", "name" : "Kalika", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Khatri", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BhupendraTopPuni", "name" : "Bhupendra", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Laxmi", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "TulsaTopPuni", "name" : "Tulsa", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Pathak", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "YamTopPuni", "name" : "Yam Bahadur", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Muna", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "ShushilaTopPuni", "name" : "Shushila", "gender" : "Female", "parent" : "TopAmarUnkn", "spouse" : "Bhusal", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "HariTopPuni", "name" : "Hari", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Meena", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "MadhuTopPuni", "name" : "Madhu", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Anita", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PrakashTopPuni", "name" : "Prakash", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BalaramTopPuni", "name" : "Balaram", "gender" : "Male", "parent" : "TopAmarUnkn", "spouse" : "Dila", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "JagatOmBDrup", "name" : "Jagat Bahadur", "gender" : "Male", "parent" : "OmTopPuni", "spouse" : "Jeenudevi", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "JyotiJagaJeen", "name" : "Jyoti", "gender" : "Female", "parent" : "JagatOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "HelinaJagaJeen", "name" : "Helina", "gender" : "Female", "parent" : "JagatOmBDrup", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "JelinaJagaJeen", "name" : "Jelina", "gender" : "Female", "parent" : "JagatOmBDrup", "spouse" : "Prasain", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SangamJagaJeen", "name" : "Sangam", "gender" : "Male", "parent" : "JagatOmBDrup", "spouse" : "Dicha", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BhagwatiOmBDrup", "name" : "Bhagwati", "gender" : "Female", "parent" : "OmTopPuni", "spouse" : "K.C.", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "ChandroOmBDrup", "name" : "Chandro", "gender" : "Female", "parent" : "OmTopPuni", "spouse" : "G.C.", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "DilOmBDrup", "name" : "Dil Bahadur", "gender" : "Male", "parent" : "OmTopPuni", "spouse" : "Pabitra", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SabitaDilPabi", "name" : "Sabita", "gender" : "Female", "parent" : "DilOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "NakitaDilPabi", "name" : "Nakita", "gender" : "Female", "parent" : "DilOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SandipDilPabi", "name" : "Sandip", "gender" : "Male", "parent" : "DilOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "Kathmandu,Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "TilOmBDrup", "name" : "Til Bahadur", "gender" : "Male", "parent" : "OmTopPuni", "spouse" : "Meena", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "AshmitaTilMeen", "name" : "Ashmita", "gender" : "Female", "parent" : "TilOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AnupTilMeen", "name" : "Anup", "gender" : "Male", "parent" : "TilOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AnkitaTilMeen", "name" : "Ankita", "gender" : "Female", "parent" : "TilOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "LalOmBDrup", "name" : "Lal Bahadur", "gender" : "Male", "parent" : "OmTopPuni", "spouse" : "Khimkala", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PrajwalLalKhim", "name" : "Prajwal", "gender" : "Male", "parent" : "LalOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PraveendLalKhim", "name" : "Praveend", "gender" : "Male", "parent" : "LalOmBDrup", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TekOmBDrup", "name" : "Tek Bahadur", "gender" : "Male", "parent" : "OmTopPuni", "spouse" : "Kalpana", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GeetaOmBDrup", "name" : "Geeta", "gender" : "Female", "parent" : "OmTopPuni", "spouse" : "G.C.", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BaburamBhupYam", "name" : "Baburam", "gender" : "Male", "parent" : "BhupalTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "DhalBhupYam", "name" : "Dhal Bahadur", "gender" : "Male", "parent" : "BhupalTopPuni", "spouse" : "Leela", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PratimaDhalLeel", "name" : "Pratima", "gender" : "Female", "parent" : "DhalBhupYam", "spouse" : "Saud", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PradeepDhalLeel", "name" : "Pradeep", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "PramilaDhalLeel", "name" : "Pramila", "gender" : "Female", "parent" : "DhalBhupYam", "spouse" : "Pachain", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "RandeepDhalLeel", "name" : "Randeep", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BalkumariDhalLeel", "name" : "Balkumari", "gender" : "Female", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "BasantDhalLeel", "name" : "Basant Jang", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "Gulmi, Nepal", "notes" : "", "currentlocation" : "" },
  { "id" : "SitalDhalLeel", "name" : "Sital Singh", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NirmalDhalLeel", "name" : "Nirmal", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DevDhalLeel", "name" : "Dev Bahadur", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MilanDhalLeel", "name" : "Milan", "gender" : "Male", "parent" : "DhalBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RudraBhupYam", "name" : "Rudra Bahadur", "gender" : "Male", "parent" : "BhupalTopPuni", "spouse" : "Sharda-Kamala", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RoshaniRudrShar", "name" : "Roshani", "gender" : "Female", "parent" : "RudraBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SaradRudrShar", "name" : "Sarad", "gender" : "Male", "parent" : "RudraBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SuryaBhupYam", "name" : "Surya", "gender" : "Male", "parent" : "BhupalTopPuni", "spouse" : "Rita", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SameerSuryRita", "name" : "Sameer", "gender" : "Male", "parent" : "SuryaBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DhurbaBhupYam", "name" : "Dhurba", "gender" : "Male", "parent" : "BhupalTopPuni", "spouse" : "Sita-Geeta", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BimalDhurSita", "name" : "Bimal", "gender" : "Male", "parent" : "DhurbaBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RayanDhurSita", "name" : "Rayan", "gender" : "Male", "parent" : "DhurbaBhupYam", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MeenaBhupYam", "name" : "Meena", "gender" : "Female", "parent" : "BhupalTopPuni", "spouse" : "Poudel Chetri", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GangaBhupYam", "name" : "Ganga", "gender" : "Female", "parent" : "BhupalTopPuni", "spouse" : "Karki", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SherDurgMeen", "name" : "Sher Bahadur", "gender" : "Male", "parent" : "DurgaTopPuni", "spouse" : "Sumitra", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BipinSherSumi", "name" : "Bipin Jang", "gender" : "Male", "parent" : "SherDurgMeen", "spouse" : "Anita", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AmitSherSumi", "name" : "Amit", "gender" : "Male", "parent" : "SherDurgMeen", "spouse" : "Anju", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "JanishaBipiAnit", "name" : "Janisha", "gender" : "Female", "parent" : "BipinSherSumi", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SamitBipiAnit", "name" : "Samit", "gender" : "Male", "parent" : "BipinSherSumi", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SubhsanaBipiAnit", "name" : "Subhsana", "gender" : "Female", "parent" : "BipinSherSumi", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ShantiDurgMeen", "name" : "Shanti", "gender" : "Female", "parent" : "DurgaTopPuni", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ShardaDurgMeen", "name" : "Sharda", "gender" : "Female", "parent" : "DurgaTopPuni", "spouse" : "G.C.", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SaraswatiDurgMeen", "name" : "Saraswati", "gender" : "Female", "parent" : "DurgaTopPuni", "spouse" : "Kunwar", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DipendraDurgMeen", "name" : "Dipendra", "gender" : "Male", "parent" : "DurgaTopPuni", "spouse" : "Rama", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AshishDipeRama", "name" : "Ashish", "gender" : "Male", "parent" : "DipendraDurgMeen", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AnkitDipeRama", "name" : "Ankit", "gender" : "Male", "parent" : "DipendraDurgMeen", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AnkitaDipeRama", "name" : "Ankita", "gender" : "Female", "parent" : "DipendraDurgMeen", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TejendraDurgMeen", "name" : "Tejendra", "gender" : "Male", "parent" : "DurgaTopPuni", "spouse" : "Sujata", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ShovaDurgMeen", "name" : "Shova", "gender" : "Female", "parent" : "DurgaTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SujanBhupLaxm", "name" : "Sujan", "gender" : "Male", "parent" : "BhupendraTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SujataBhupLaxm", "name" : "Sujata", "gender" : "Female", "parent" : "BhupendraTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SurakshaBhupLaxm", "name" : "Suraksha", "gender" : "Female", "parent" : "BhupendraTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SumanBhupLaxm", "name" : "Suman", "gender" : "Female", "parent" : "BhupendraTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SachinYamMuna", "name" : "Sachin", "gender" : "Male", "parent" : "YamTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SachinaYamMuna", "name" : "Sachina", "gender" : "Female", "parent" : "YamTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SuvechhaHariMeen", "name" : "Suvechha", "gender" : "Female", "parent" : "HariTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AkritiBalaDila", "name" : "Akriti", "gender" : "Female", "parent" : "BalaramTopPuni", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TopAmarUnkn", "name" : "Top Bahadur", "gender" : "Male", "parent" : "AmarBilaUnkn", "spouse" : "Puni-Balkumari-Khagisara", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AbhimanAmarUnkn", "name" : "Abhiman", "gender" : "Male", "parent" : "AmarBilaUnkn", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "LuckyAmarUnkn", "name" : "Lucky", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "KhimkaliAmarUnkn", "name" : "Khimkali", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MemandariAmarUnkn", "name" : "Memandari", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PurnaKaliAmarUnkn", "name" : "PurnaKali", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "Gharti", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TaraAmarUnkn", "name" : "Tara", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "Mahat", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "HimkumariAmarUnkn", "name" : "Himkumari", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "Khatri", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NarAmarUnkn", "name" : "Nar", "gender" : "Male", "parent" : "AmarBilaUnkn", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ParwatiAmarUnkn", "name" : "Parwati", "gender" : "Female", "parent" : "AmarBilaUnkn", "spouse" : "Khatri", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AmarBilaUnkn", "name" : "Amar Singh", "gender" : "Male", "parent" : "BilabhadraBalbUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BagdalBilaUnkn", "name" : "Bagdal", "gender" : "Male", "parent" : "BilabhadraBalbUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "JarsioonBilaUnkn", "name" : "Jarsioon", "gender" : "Male", "parent" : "BilabhadraBalbUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RanjeetBilaUnkn", "name" : "Ranjeet", "gender" : "Male", "parent" : "BilabhadraBalbUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "JangaveerBilaUnkn", "name" : "Jangaveer", "gender" : "Male", "parent" : "BilabhadraBalbUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "LaliJarsUnkn", "name" : "Lali", "gender" : "Female", "parent" : "JarsioonBilaUnkn", "spouse" : "Acharya", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TulRanjUnkn", "name" : "Tul Bahadur", "gender" : "Male", "parent" : "RanjeetBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NandaramRanjUnkn", "name" : "Nandaram", "gender" : "Male", "parent" : "RanjeetBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DalveerRanjUnkn", "name" : "Dalveer", "gender" : "Male", "parent" : "RanjeetBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "HarilalRanjUnkn", "name" : "Harilal", "gender" : "Male", "parent" : "RanjeetBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RanTulUnkn", "name" : "Ran Bahadur", "gender" : "Male", "parent" : "TulRanjUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MaiyanJangUnkn", "name" : "Maiyan Singh", "gender" : "Male", "parent" : "JangaveerBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "HarilalJangUnkn", "name" : "Harilal", "gender" : "Male", "parent" : "JangaveerBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BhupalJangUnkn", "name" : "Bhupal Singh", "gender" : "Male", "parent" : "JangaveerBilaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RabilalMaiyUnkn", "name" : "Rabilal", "gender" : "Male", "parent" : "MaiyanJangUnkn", "spouse" : "Jhabi", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BhimMaiyUnkn", "name" : "Bhim Bahadur", "gender" : "Male", "parent" : "MaiyanJangUnkn", "spouse" : "Khagi", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BhumaRabiJhab", "name" : "Bhuma", "gender" : "Female", "parent" : "RabilalMaiyUnkn", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GopalRabiJhab", "name" : "Gopal Bahadur", "gender" : "Male", "parent" : "RabilalMaiyUnkn", "spouse" : "Harikala-Geeta-Sita", "DOB" : "?", "birthplace" : "?", "notes" : "Moved to Suwal Oak Nagarpalika", "currentlocation" : "" },
  { "id" : "GangaGopaHari", "name" : "Ganga", "gender" : "Male", "parent" : "GopalRabiJhab", "spouse" : "Uma", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MitraGopaHari", "name" : "Mitra Bahadur", "gender" : "Male", "parent" : "GopalRabiJhab", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PappuGopaHari", "name" : "Pappu", "gender" : "Male", "parent" : "GopalRabiJhab", "spouse" : "Harikala", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GeetaGopaHari", "name" : "Geeta", "gender" : "Female", "parent" : "GopalRabiJhab", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NepalGopaHari", "name" : "Nepal", "gender" : "Male", "parent" : "GopalRabiJhab", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SurajGangUma", "name" : "Suraj", "gender" : "Male", "parent" : "GangaGopaHari", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ChuniyaGangUma", "name" : "Chuniya", "gender" : "Female", "parent" : "GangaGopaHari", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PadamGangUma", "name" : "Padam", "gender" : "Male", "parent" : "GangaGopaHari", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PratimaPappHari", "name" : "Pratima", "gender" : "Female", "parent" : "PappuGopaHari", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PeterPappHari", "name" : "Peter Jung", "gender" : "Male", "parent" : "PappuGopaHari", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NamiBhimKhag", "name" : "Nami", "gender" : "Female", "parent" : "BhimMaiyUnkn", "spouse" : "Khatri", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NarBhimKhag", "name" : "Nar Bahadur", "gender" : "Male", "parent" : "BhimMaiyUnkn", "spouse" : "Tulsi", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "KalikaBhimKhag", "name" : "Kalika", "gender" : "Female", "parent" : "BhimMaiyUnkn", "spouse" : "Basnet", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NetraNarTuls", "name" : "Netra", "gender" : "Female", "parent" : "NarBhimKhag", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TekNarTuls", "name" : "Tek Bahadur", "gender" : "Male", "parent" : "NarBhimKhag", "spouse" : "Geeta", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GyanNarTuls", "name" : "Gyan Bahadur", "gender" : "Male", "parent" : "NarBhimKhag", "spouse" : "Jeevkali", "DOB" : "?", "birthplace" : "?", "notes" : "Moved to Nawalparasi, Suwnal", "currentlocation" : "" },
  { "id" : "SabitraNarTuls", "name" : "Sabitra", "gender" : "Female", "parent" : "NarBhimKhag", "spouse" : "Pathak", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RamNarTuls", "name" : "Ram", "gender" : "Male", "parent" : "NarBhimKhag", "spouse" : "Sita", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SunitaTekGeet", "name" : "Sunita", "gender" : "Female", "parent" : "TekNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RoshanTekGeet", "name" : "Roshan", "gender" : "Male", "parent" : "TekNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SindhuTekGeet", "name" : "Sindhu", "gender" : "Female", "parent" : "TekNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DarshanGyanJeev", "name" : "Darshan", "gender" : "Male", "parent" : "GyanNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BinayGyanJeev", "name" : "Binay", "gender" : "Male", "parent" : "GyanNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RupaGyanJeev", "name" : "Rupa", "gender" : "Female", "parent" : "GyanNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DeepaGyanJeev", "name" : "Deepa", "gender" : "Female", "parent" : "GyanNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PushpaGyanJeev", "name" : "Pushpa", "gender" : "Female", "parent" : "GyanNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PrakashGyanJeev", "name" : "Prakash", "gender" : "Male", "parent" : "GyanNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GyanRajRamSita", "name" : "GyanRaj", "gender" : "Male", "parent" : "RamNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SharmilaRamSita", "name" : "Sharmila", "gender" : "Female", "parent" : "RamNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SampratRamSita", "name" : "Samprat", "gender" : "Male", "parent" : "RamNarTuls", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "KhunteNandUnkn", "name" : "Khunte", "gender" : "Male", "parent" : "NandaramRanjUnkn", "spouse" : "Shiva", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MangaliKhunShiv", "name" : "Mangali", "gender" : "Female", "parent" : "KhunteNandUnkn", "spouse" : "K.C.", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PurnaKhunShiv", "name" : "Purna Bahadur", "gender" : "Male", "parent" : "KhunteNandUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "Had two songs and moved to Silang, India", "currentlocation" : "" },
  { "id" : "PremKhunShiv", "name" : "Prem Bahadur", "gender" : "Male", "parent" : "KhunteNandUnkn", "spouse" : "Mankumari", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ChandriKhunShiv", "name" : "Chandri", "gender" : "Female", "parent" : "KhunteNandUnkn", "spouse" : "K.C.", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TulKhunShiv", "name" : "Tul Bahadur", "gender" : "Male", "parent" : "KhunteNandUnkn", "spouse" : "Lalkumari", "DOB" : "?", "birthplace" : "?", "notes" : "Childern of Tul Bahadur moved to Pakistan", "currentlocation" : "" },
  { "id" : "TopKhunShiv", "name" : "Top Bahadur", "gender" : "Male", "parent" : "KhunteNandUnkn", "spouse" : "Harikala", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GorePremMank", "name" : "Gore", "gender" : "Male", "parent" : "PremKhunShiv", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BhupePremMank", "name" : "Bhupe", "gender" : "Male", "parent" : "PremKhunShiv", "spouse" : "Chandri", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BijuliGoreUnkn", "name" : "Bijuli", "gender" : "Female", "parent" : "GorePremMank", "spouse" : "Khatri", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BomBhupChan", "name" : "Bom Bahadur", "gender" : "Male", "parent" : "BhupePremMank", "spouse" : "Beena", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RakeshBomBeen", "name" : "Rakesh", "gender" : "Male", "parent" : "BomBhupChan", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RoshaniBomBeen", "name" : "Roshani", "gender" : "Female", "parent" : "BomBhupChan", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "RomanBomBeen", "name" : "Roman", "gender" : "Male", "parent" : "BomBhupChan", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GovindTulLalk", "name" : "Govind", "gender" : "Male", "parent" : "TulKhunShiv", "spouse" : "Balkumari", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PrithiviTulLalk", "name" : "Prithivi", "gender" : "Male", "parent" : "TulKhunShiv", "spouse" : "Chameli", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PremGoviBalk", "name" : "Prem", "gender" : "Male", "parent" : "GovindTulLalk", "spouse" : "Hema", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BelaGoviBalk", "name" : "Bela", "gender" : "Female", "parent" : "GovindTulLalk", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "ManishPremHema", "name" : "Manish", "gender" : "Male", "parent" : "PremGoviBalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MunaPremHema", "name" : "Muna", "gender" : "Female", "parent" : "PremGoviBalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MukeshPremHema", "name" : "Mukesh", "gender" : "Male", "parent" : "PremGoviBalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "KaushilaPritCham", "name" : "Kaushila", "gender" : "Female", "parent" : "PrithiviTulLalk", "spouse" : "Thapa", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "GangaPritCham", "name" : "Ganga", "gender" : "Male", "parent" : "PrithiviTulLalk", "spouse" : "Sita", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "PremPritCham", "name" : "Prem", "gender" : "Male", "parent" : "PrithiviTulLalk", "spouse" : "Bima", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "JamunaPritCham", "name" : "Jamuna", "gender" : "Female", "parent" : "PrithiviTulLalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BuddhaPritCham", "name" : "Buddha", "gender" : "Male", "parent" : "PrithiviTulLalk", "spouse" : "Sabitra", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "DamayantiPritCham", "name" : "Damayanti", "gender" : "Female", "parent" : "PrithiviTulLalk", "spouse" : "Khadka", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "NarayanPritCham", "name" : "Narayan", "gender" : "Male", "parent" : "PrithiviTulLalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "MadhuPritCham", "name" : "Madhu", "gender" : "Male", "parent" : "PrithiviTulLalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AnilPritCham", "name" : "Anil", "gender" : "Male", "parent" : "PrithiviTulLalk", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "KunalGangSita", "name" : "Kunal", "gender" : "Male", "parent" : "GangaPritCham", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "KopilGangSita", "name" : "Kopil", "gender" : "Male", "parent" : "GangaPritCham", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TusharPremBima", "name" : "Tushar", "gender" : "Male", "parent" : "PremPritCham", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "TekPremBima", "name" : "Tek Bahadur", "gender" : "Male", "parent" : "PremPritCham", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SujataBuddSabi", "name" : "Sujata", "gender" : "Female", "parent" : "BuddhaPritCham", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "SujanBuddSabi", "name" : "Sujan", "gender" : "Male", "parent" : "BuddhaPritCham", "spouse" : "NA", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BilabhadraBalbUnkn", "name" : "Bilabhadra Singh", "gender" : "Male", "parent" : "BalbhadraHemaUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BahadurHemaUnkn", "name" : "Bahadur", "gender" : "Male", "parent" : "HemantUnknUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "BalbhadraHemaUnkn", "name" : "Balbhadra", "gender" : "Male", "parent" : "HemantUnknUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "VeerHemaUnkn", "name" : "Veer Bhanjan", "gender" : "Male", "parent" : "HemantUnknUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "AjabHemaUnkn", "name" : "Ajab Singh", "gender" : "Male", "parent" : "HemantUnknUnkn", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" },
  { "id" : "HemantUnknUnkn", "name" : "Hemant Singh", "gender" : "Male", "parent" : "null", "spouse" : "Unknown", "DOB" : "?", "birthplace" : "?", "notes" : "", "currentlocation" : "" }
];